# Generated by Django 5.1.4 on 2024-12-18 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_symbol', models.CharField(max_length=10)),
                ('daily_net_position', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='StockPriceBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_symbol', models.CharField(max_length=10)),
                ('security_name', models.CharField(max_length=500)),
                ('market_category', models.CharField(max_length=100)),
                ('test_issue', models.CharField(max_length=10)),
                ('financial_status', models.CharField(max_length=10)),
                ('round_lot_size', models.CharField(max_length=10)),
                ('etf', models.CharField(max_length=10)),
                ('next_shares', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_symbol', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('direction', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TradeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField()),
                ('level', models.CharField(choices=[('excel_file', 'Excel File'), ('excel_row', 'Excel Row'), ('fyahoo_api_call', 'FYahoo Api Call'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('stockpricebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading.stockpricebase')),
                ('dividents', models.FloatField()),
                ('stock_split', models.FloatField()),
            ],
            bases=('trading.stockpricebase',),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stockpricebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading.stockpricebase')),
                ('adj_close', models.FloatField()),
            ],
            bases=('trading.stockpricebase',),
        ),
    ]
