# Generated by Django 5.1.4 on 2024-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company_symbol', models.CharField(max_length=10)),
                ('added_cost', models.FloatField()),
                ('removed_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('unit_quantity', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='dailynetposition',
            name='daily_net_position',
            field=models.FloatField(),
        ),
    ]
